### PR TITLE
Replacement callback & row-based filtering

### PR DESCRIPTION
**Pull request by drzraf**
- Reroll of #104 ( Feature: Call user function with --callback flag #104 )
- Preliminary work for #127 (Callback access to current primary key & column)
- Include #125 (Introduce `--where` flag)

### CODE REVIEW

**Comment by schlessera** [comment]
@drzraf Is this still a work-in-progress ? If not, can you do the necessary style changes to make PHPCS happy? Running `vendor/bin/phpcbf` should already fix a large portion of them.

See here: https://travis-ci.org/wp-cli/search-replace-command/jobs/586606309#L591-L709

**Comment by drzraf** [comment]
Just did^

**Comment by drzraf** [comment]
Could you please have a look. It was a huge MR update and I'll hardly find the motivation to further rework/update it again if merge-conflicts arised. It's also rare to have an opportunity window to test changes.

**Comment by drzraf** [comment]
ping

**Comment by schlessera** [comment]
@drzraf The code looks good so far, and I'd love to merge this. However, for merging it, we'll need tests as well that cover all the main code paths. Are you able to add such tests?

**Comment by schlessera** [comment]
Note: the Travis issues should be resolved by now.

**Comment by drzraf** [comment]
Hi @schlessera , I completely understand your concern given the shape of the diff.
Sadly I'm not working with this command these days and have literally no-time I could dedicate to further refine the PR with test; sorry.

**Comment by schlessera** [comment]
Thanks for the quick response! I'll see if I can manage to add the tests myself to get this included.

**Comment by drzraf** [comment]
Would you merge if I were to rebase it once again?

**Comment by davidwebca** [comment]
Has this seen any update at all lately? I need to find a solution to search-replace by excluding revisions. 🤔

**Comment by danielbachhuber** [comment]
@davidwebca Want to open a new pull request with this code and tests covering the change?

**Comment by davidwebca** [comment]
I'll a see what I can do!

**Comment by drzraf** [comment]
@danielbachhuber : What about providing writing tests since upstream are the ones who know how to best write them?

I'd later see and possibly spend the necessary hours for another rebase.

**Comment by danielbachhuber** [comment]
Proceeding with https://github.com/wp-cli/wp-cli/issues/5594 for this repository. I've captured this PR to https://gist.github.com/danielbachhuber/39778759a59cb231c94520e38ae3f6ba in case this PR is auto-closed or broken in some way.

**Comment by davidwebca** [comment]
@danielbachhuber Completely had forgotten about this. Do you have any guides or examples of tests (following up that conversation higher here?)

**Comment by danielbachhuber** [comment]
@davidwebca Here's our guide to writing tests: https://make.wordpress.org/cli/handbook/contributions/pull-requests/#running-and-writing-tests

There are plenty of examples within this and other repos. Feel free to stop by `#cli` in WordPress.org Slack with any questions you might have.

Also, specific to this pull request: I think a filter-based approach would work best for this need.

**Pull request closed without merging**
