### PR TITLE
Adapt package for framework v2

### LINKED ISSUE #85: Move command over to new v2 structure
The following changes need to be made to move the command over to the v2 structure:

- [ ] Make sure the correct framework is required:
  ```
  composer require wp-cli/wp-cli:^2
  ```
- [ ] Require the testing framework as a dev dependency:
  ```
  composer require --dev wp-cli/wp-cli-tests:^0
  ```
- [ ] Use the `.travis.yml` file from `wp-cli/wp-cli`:
  ```
  wget https://raw.githubusercontent.com/wp-cli/wp-cli/master/.travis.yml
  ```
- [ ] Add the default script configuration to Composer file:
  ```
    "scripts": {
        "lint": "run-linter-tests",
        "phpcs": "run-phpcs-tests",
        "phpunit": "run-php-unit-tests",
        "behat": "run-behat-tests",
        "prepare-tests": "install-package-tests",
        "test": [
            "@lint",
            "@phpcs",
            "@phpunit",
            "@behat"
        ]
    },
  ```
- [ ] Remove scaffolded binary files:
  ```
  git rm bin/install-package-tests.sh
  git rm bin/test.sh
  ```
- [ ] Remove scaffolded Behat setup:
  ```
  git rm features/bootstrap/*
  git rm features/extra/*
  git rm features/steps/*
  ```
- [ ] Remove scaffolded Behat tags util script:
  ```
  git rm utils/behat-tags.php
  ```
- [ ] Add command packages that are needed for Behat tests as `--dev` dependencies.
  The following commands are already available, anything else needs to be explicitly required:
  - `cli *`
  - `config *`
  - `core *`
  - `eval`
  - `eval-file`
  - `help`
- [ ] Update all dependencies:
  ```
  composer update
  ```
- [ ] *Optional* - Add PHPCS rule set to enable CS & compatibility sniffing:
  ```
  wget https://raw.githubusercontent.com/wp-cli/wp-cli/master/phpcs.xml.dist
  ```
- [ ] Run and adapt tests to make sure they all pass:
  ```
  composer test
  ```

### PR DESCRIPTION
**Pull request by schlessera**
Fixes #85

### CODE REVIEW

**Comment by swissspidy** [comment]
Getting the following error now when running the tests:

```
01. $ wp db import wordpress.sql
    
    ERROR 1067 (42000) at line 14 in file: 'wordpress.sql': Invalid default value for 'comment_date'
    cwd: /var/folders/c1/8bn4rqzx0h1f49bxgmrzk2hm0000gn/T/wp-cli-test-run-search-replace-export.feature.3-5b65b9e29de725.05330330/
    run time: 0.36528205871582
    exit status: 1
    In step `And I run `wp db import wordpress.sql`'.  # vendor/wp-cli/wp-cli-tests/features/steps/when.php:29
    From scenario `Search / replace export to STDOUT'. # features/search-replace-export.feature:3
    Of feature `Search / replace with file export'.
```

No idea how that got broken.

**Comment by wojsmol** [comment]
missing wp import

**Comment by swissspidy** [comment]
@wojsmol Nope, that's not it. Just tested. The format of the exported SQL file really seems to be off.

**Comment by swissspidy** [comment]
It's probably because I run MySQL 8 locally, and apparently in strict mode:

```
mysql> SHOW VARIABLES LIKE 'sql_mode';
+---------------+-----------------------------------------------------------------------------------------------------------------------+
| Variable_name | Value                                                                                                                 |
+---------------+-----------------------------------------------------------------------------------------------------------------------+
| sql_mode      | ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION |
+---------------+-----------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)
```


See https://dev.mysql.com/doc/refman/8.0/en/timestamp-initialization.html and https://stackoverflow.com/questions/36374335/error-in-mysql-when-setting-default-value-for-date-or-datetime.

So this is more of a bug in WordPress's default db schema than in this command.

**Pull request merged**
