### PR TITLE
Patch 61

### PR DESCRIPTION
**Pull request by alpipego**
@miya0001 please see my #wcbkk changes, I have not yet update the tests; but I'll be glad to continue working on updating them also.

### CODE REVIEW

**Comment by gitlost** [comment]
Thanks for the PR @alpipego but as this is being dealt with already in https://github.com/wp-cli/search-replace-command/pull/62 I think it's best to leave it there. I do like your `$match_cnt` suggestion though and will note it on the original PR, ta!

**Comment by gitlost** [comment]
I should add @alpipego that there're loads of other issues around where your contribution would be most welcome...

**Comment by alpipego** [comment]
@gitlost the PR was against `patch-61`. It incorporates your suggested changes on #62.

This is the result of WordCamp Bangkok Contributer Day where @miya0001 is leading the WPCLI team.

**Comment by gitlost** [comment]
Okay so the easiest thing to do is to re-open this PR and close https://github.com/wp-cli/search-replace-command/pull/62 ?

**Comment by alpipego** [comment]
I thought merging it with #62 would be easiest, as I have not updated the tests (@miya0001 is going to do that on #62). 

Moreover he didn't create the PR from a fork... Otherwise I'd have created the PR against @miya0001's remote (if that does make any sense).

**Comment by miya0001** [comment]
Thanks @alpipego for your contribution.
I merge this PR into #62 for now.

**Pull request merged**
