### PR TITLE
Fix/report improvements

### PR DESCRIPTION
**Pull request by LC43**
Hi, i had this stalled waiting for a reply on slack :$

I think this condition for the report being printed is more complete.

### CODE REVIEW

**Comment by danielbachhuber** [comment]
@LC43 Can you merge master please?

@gitlost Can you make a judgement on this when you have a moment?

**Comment by LC43** [comment]
Hi @danielbachhuber, done.

i would like to discuss that, since `--report` is true by default, when doing `if ( $this->report )` is not enough, because if you pass `--report=false` is still seen as true ( false is passed as a string ).

Thanks why i used it separately:
```
if ( $this->report_changed_only ) {
	continue;
}
```
there's another places where the `if ( $this->report )`  condition is made. 

If i'm not wrong, i think doing  `if ( true == $this->report ) {` would be the correct way to treat this or change  the parsing of false parameters?

**Comment by gitlost** [comment]
Thanks for the PR @LC43.

Re not outputting a warning if `report_changed_only` set then the behaviour here is probably more what people wanted from https://github.com/wp-cli/search-replace-command/pull/54, so https://github.com/wp-cli/search-replace-command/pull/55/commits/b69fb964b459a9657a91f4e41f40caf965a70551 looks good to me. A functional test would be nice though.

Re the flag issue I don't see this as necessary. Doing `--report=false` is not currently supported as a way to set a flag to false. If we want to support that (and it may be a good idea to) then it should be done at the framework level.

**Comment by LC43** [comment]
thanks for the review @gitlost .

i'll close this one and add a new with b69fb96 . but can i keep the 2adf235 too ?

**Comment by gitlost** [comment]
> i'll close this one and add a new

If that's handier for you @LC43, though you could just use this one.

> can i keep the 2adf235 too 

Sorry missed that - not printing any report if there's nothing to report looks like desired behaviour to me, though technically it's not BC. I can't see it causing issues for scripts so it's probably cool, @danielbachhuber ? Again a functional test for this behaviour would be good.

**Comment by danielbachhuber** [comment]
> Sorry missed that - not printing any report if there's nothing to report looks like desired behaviour to me, though technically it's not BC.

Just to take a step back, in what usage scenarios would this be the case?

**Comment by gitlost** [comment]
It's if the search doesn't match anything. So given
```
vendor/bin/wp --path=/var/www/wptest search-replace not_found dummy --report-changed-only
```
without the `! empty( $report )` check you currently get an empty table:
```
+-------+--------+--------------+------+
| Table | Column | Replacements | Type |
+-------+--------+--------------+------+
+-------+--------+--------------+------+
Success: 0 replacements to be made.
```

With the `! empty( $report )` check https://github.com/wp-cli/search-replace-command/commit/2adf235e0f85df33e5a098b968e5a2be3c625234 you don't get an empty table, just:
```
Success: 0 replacements to be made.
```

**Comment by danielbachhuber** [comment]
Ok, works for me.

**Pull request closed without merging**
